name: icons_utils
description: A sample command-line application.
version: 1.0.1
repository: https://github.com/Lafannn/icons_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.1.1
  yaml: ^3.1.0
  dio: ^4.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
